name: Generate PetStore Client
on: push
jobs:
  generateClient:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Swagger Codegen
      with:
        swagger_file: http://petstore.swagger.io/v2/swagger.json
        output_dir: ./generated-example
        generator_language: typescript-fetch
      uses: ./
    - uses: stefanzweifel/git-auto-commit-action@dev
      with:
        commit_author_email: david.t.rowe@gmail.com
        commit_author_name: Rowebot
        commit_message: Apply automatic changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


