name: Generate PetStore Client
on: push
jobs:
  generateClient:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      run: git checkout "${GITHUB_REF:11}"
    - name: Swagger Codegen
      uses: ./
      with:
        swagger_file: http://petstore.swagger.io/v2/swagger.json
        output_dir: ./generated-example
        generator_language: typescript-fetch
    - name: TEMPORTARY - Fix commit
      run: git remote set-url origin https://${{ secrets.PAT_TOKEN }}:x-oauth-basic@github.com/Offtree/swagger-codegen-action
    - uses: stefanzweifel/git-auto-commit-action@dev
      with:
        commit_author_email: david.t.rowe@gmail.com
        commit_author_name: Rowebot
        commit_message: Apply automatic changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


